import AppKit
import SwiftUI
import Testing
import Observation
@testable import SysDataMenu

@MainActor
@Suite struct ScrollLayoutTests {
    @Test(.enabled(if: ProcessInfo.processInfo.environment["SYSDATA_UI_TESTS"] == "1"))
    func scanBatchesSurviveScrolling() throws {
        NSApplication.shared.setActivationPolicy(.prohibited)
        let items = (0..<180).map { index in
            StorageItem(
                id: "scroll-fixture-\(index)", category: StorageCategory.allCases[5 - index / 30],
                name: "Cache: Example application \(index)",
                detail: index.isMultiple(of: 3) ? "Regenerated by the app." :
                    "Symbols and cached downloads for an application with a long description. Rebuilt on the next launch.",
                sizeBytes: Int64(180 - index) * 123_456_789,
                safety: .safe, action: .removePaths([]),
                revealURL: URL(fileURLWithPath: "/nonexistent/scroll-fixture-\(index)"),
                lastModified: index.isMultiple(of: 2) ? Date(timeIntervalSince1970: 1_600_000_000) : nil
            )
        }
        let state = ScanRows()
        state.items = Array(items.prefix(30))
        let host = NSHostingView(rootView: ScanInventory(state: state).frame(width: 460, height: 480))
        let window = NSWindow(contentRect: NSRect(x: -10000, y: -10000, width: 460, height: 480),
                              styleMask: .borderless, backing: .buffered, defer: false)
        window.isReleasedWhenClosed = false
        window.contentView = host
        window.orderBack(nil)
        defer { window.close() }
        func settle() {
            for _ in 0..<3 {
                window.layoutIfNeeded()
                host.layoutSubtreeIfNeeded()
                window.displayIfNeeded()
                RunLoop.main.run(until: Date(timeIntervalSinceNow: 0.02))
            }
        }
        settle()
        func findScroll(_ view: NSView) -> NSScrollView? {
            if let scroll = view as? NSScrollView { return scroll }
            for child in view.subviews { if let scroll = findScroll(child) { return scroll } }
            return nil
        }
        let scroll = try #require(findScroll(host))
        let document = try #require(scroll.documentView)
        #expect(document.bounds.height > scroll.contentSize.height)
        for step in 0..<90 {
            // Simulate asynchronous probe completions between scroll events.
            // New categories precede existing rows, just as in the real scan.
            if step < 30 {
                state.items = Array(items.prefix(min(180, 30 + step * 6)))
            }
            if step == 35 {
                state.items = state.items.map { item in
                    StorageItem(id: item.id, category: item.category, name: item.name,
                                detail: item.detail + " Updated scan result with additional details.",
                                sizeBytes: item.sizeBytes, safety: item.safety, action: item.action,
                                revealURL: item.revealURL, lastModified: item.lastModified)
                }
            }
            let maxY = max(0, document.bounds.height - scroll.contentSize.height)
            scroll.contentView.scroll(to: NSPoint(x: 0, y: maxY * CGFloat(step % 30) / 29))
            scroll.reflectScrolledClipView(scroll.contentView)
            let wheel = try #require(CGEvent(scrollWheelEvent2Source: nil, units: .pixel,
                                            wheelCount: 1, wheel1: step < 45 ? -80 : 80,
                                            wheel2: 0, wheel3: 0))
            scroll.scrollWheel(with: try #require(NSEvent(cgEvent: wheel)))
            settle()
        }
        #expect(state.items.count == 180)
        #expect(scroll.contentView.bounds.origin.y > 0)
    }
}

@MainActor
@Observable
private final class ScanRows {
    var items: [StorageItem] = []
}

private struct ScanInventory: View {
    var state: ScanRows

    var body: some View {
        InventoryList {
            ForEach(StorageCategory.allCases, id: \.self) { category in
                let members = state.items.filter { $0.category == category }
                if !members.isEmpty {
                    Text(category.title).fontWeight(.semibold)
                    ForEach(members.sorted { ($0.sizeBytes ?? 0) > ($1.sizeBytes ?? 0) }) { item in
                        ItemRow(item: item, change: nil, isBusy: false, isSelected: false,
                                onToggle: { _ in }, onDelete: {}, onHide: {})
                    }
                }
            }
        }
    }
}
