import AppKit
import SwiftUI
import Testing
@testable import SysDataMenu

@MainActor
@Suite struct ScrollLayoutTests {
    @Test(.enabled(if: ProcessInfo.processInfo.environment["SYSDATA_UI_TESTS"] == "1"))
    func variableHeightRowsSurviveScrolling() throws {
        NSApplication.shared.setActivationPolicy(.prohibited)
        let items = (0..<180).map { index in
            StorageItem(
                id: "scroll-fixture-\(index)", category: .apps,
                name: "Cache: Example application \(index)",
                detail: index.isMultiple(of: 3) ? "Regenerated by the app." :
                    "Symbols and cached downloads for an application with a long description. Rebuilt on the next launch.",
                sizeBytes: Int64(180 - index) * 123_456_789,
                safety: .safe, action: .removePaths([]),
                revealURL: URL(fileURLWithPath: "/nonexistent/scroll-fixture-\(index)"),
                lastModified: index.isMultiple(of: 2) ? Date(timeIntervalSince1970: 1_600_000_000) : nil
            )
        }
        let host = NSHostingView(rootView: InventoryList {
            ForEach(items) { item in
                ItemRow(item: item, change: nil, isBusy: false, isSelected: false,
                        onToggle: { _ in }, onDelete: {}, onHide: {})
            }
        }.frame(width: 460, height: 480))
        let window = NSWindow(contentRect: NSRect(x: -10000, y: -10000, width: 460, height: 480),
                              styleMask: .borderless, backing: .buffered, defer: false)
        window.isReleasedWhenClosed = false
        window.contentView = host
        window.orderBack(nil)
        defer { window.close() }
        func settle() {
            for _ in 0..<3 {
                window.layoutIfNeeded()
                host.layoutSubtreeIfNeeded()
                window.displayIfNeeded()
                RunLoop.main.run(until: Date(timeIntervalSinceNow: 0.02))
            }
        }
        settle()
        func findScroll(_ view: NSView) -> NSScrollView? {
            if let scroll = view as? NSScrollView { return scroll }
            for child in view.subviews { if let scroll = findScroll(child) { return scroll } }
            return nil
        }
        let scroll = try #require(findScroll(host))
        let document = try #require(scroll.documentView)
        #expect(document.bounds.height > scroll.contentSize.height)
        for step in Array(0...40) + Array((0...40).reversed()) {
            let maxY = max(0, document.bounds.height - scroll.contentSize.height)
            scroll.contentView.scroll(to: NSPoint(x: 0, y: maxY * CGFloat(step) / 40))
            scroll.reflectScrolledClipView(scroll.contentView)
            settle()
        }
    }
}
